### ISSUE TITLE
it can be compiled with MSVC and compiler flag `/permissive-`

### ISSUE THREAD

**Issue by Harold2017** [Dugy/foreachStructMember#2]
[FYI](https://godbolt.org/z/boMov9sfj).
[permissive standards conformance](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170).
Actually a more easier way to implement member visitor may be enumerating structure binding instead of member offset, and certainly enumeration is more verbose XD.

**Comment by Dugy** [comment]
Thank you for the information. I remember using `/permissive-` to get a lot of metaprogramming stuff working on MSVC, but it was a long time ago and it didn't dawn on me now.

I have edited the readme to add the explanation how to make it work on MSVC.
